baseURL: https://www.pooyarazavi.com
title: Pooya Razavi
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Pooya Razavi
  avatarURL: images/N90.jpg
  colorScheme: auto
  commit: https://github.com/p-razavi/website-theme-coder/
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Pooya Razavi's personal website
  hideColorSchemeToggle: no
  info:
    - Research Scientist
  keywords: blog, R-code, research, personal
  maxSeeAlsoItems: 5
  rtl: no
  since: 2022
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/p-razavi/
      weight: 1
    #- icon: fa fa-2x fa-github
    #  name: Github
    #  url: https://github.com/p-razavi/
    #  weight: 2
    #- icon: fa fa-2x fa-twitter
    #  name: Twitter
    #  url: https://twitter.com/johndoe/
    #  weight: 3
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/pooyarazavi/
      weight: 4
    #- icon: fa fa-2x fa-medium
    #  name: Medium
    #  url: https://medium.com/@johndoe
    #  weight: 5
    #- icon: fa fa-2x fa-rss
    #  name: RSS
    #  rel: alternate
    #  type: application/rss+xml
    #  url: https://myhugosite.com/index.xml
    #  weight: 6
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':us:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: R/Python Tutorials
          url: Tutorials/
          weight: 3  
        #- name: Blog
        #  url: posts/
        #  weight: 3
        - name: Publications / Presentations
          url: pubpres/
          weight: 4
        #- name: Contact me
        #  url: contact/
        #  weight: 5
  #pt-br:
  #  languageName: ':brazil:'
  #  menu:
  #    main:
  #      - name: Sobre
  #        url: about/
  #        weight: 1
  #      - name: Blog
  #        url: posts/
  #        weight: 2
  #      - name: Projetos
  #        url: projects/
  #        weight: 3
  #      - name: Contato
  #        url: contact/
  #        weight: 5
  #  params:
  #    author: Pooya Razavi
  #    description: Sítio pessoal de Pooya Razavi
  #    info: Full Stack DevOps e Mágico
  #    keywords: blog,desenvolvedor,pessoal
  #  title: Pooya Razavi
